fix ecr script

diff --git a/scripts/ecr-public-login b/scripts/ecr-public-login
--- a/scripts/ecr-public-login
+++ b/scripts/ecr-public-login
@@ -6,4 +6,16 @@ if [[ -z "${ECR_REGISTRY}" ]]; then
     exit 1
 fi
 
-docker login --username AWS -p="$(docker run --rm --env-file <(env | grep AWS) -i amazon/aws-cli ecr-public get-login-password --region us-east-1)" ${ECR_REGISTRY}
+function exit_and_fail() {
+    echo "❌ Failed to login to ECR Public Repo!"
+}
+
+trap exit_and_fail INT TERM ERR
+
+docker run --rm \
+    -e AWS_REGION=${AWS_REGION:=""} \
+    -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:=""} \
+    -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:=""} \
+    -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:=""} \
+    -e AWS_PAGER="" \
+    -i amazon/aws-cli ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY}
